### ISSUE TITLE
Custom Preset naming / error

### ISSUE THREAD

**Issue by audetcameron** [wodby/nginx#58]
Hello there,
does this still function as expected?

```
**Custom preset**
You can use a custom by preset by mounting your preset to /etc/gotpl/presets/[my-preset-name].conf.tmpl and setting $NGINX_VHOST_PRESET=[my-preset-name].
```

I copied the [wordpress preset](https://github.com/wodby/nginx/blob/master/templates/presets/wordpress.conf.tmpl) with the intention of adding some roots/bedrock redirect logic (but have not added it yet).

my docker-compose looks like so

```
`  
nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: bedrock
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
    - ./:/var/www/html:cached
    #to add redirects for bedrock assets added to wp prior to bedrock eg: wp-content/uploads/*
    - ./bedrock.conf.tmpl:/etc/gotpl/presets/bedrock.conf.tmpl
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/wordpress/local#docker-for-mac
#    - mutagen:/var/www/html
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
`
```

my bedrock.config.tmpl is a clone of your wordpress template

the nginx container will crash with `nginx: [emerg] no port in upstream "php" in /etc/nginx/preset.conf:103`

However,  if I change bedrock.config.tmlp to wordpress.config.tmlp and update the docker-compose.yml it will copy my template over and show my changes.

My question is, Am I doing something wrong in the docker compose 
`      NGINX_VHOST_PRESET: bedrock `
to where it doesn't know what file to look for?
I can verify that the file does exist inside the container /etc/gotpl/presets/bedrock.conf.tmpl (if I set the vhost back to wordpress to keep the container running).

Thanks in advance, and not a huge issue just more of a "but how do it do" sort of situation.
Take care :)
