### ISSUE TITLE
defaults.conf always generates 50x pages location

### ISSUE THREAD

**Issue by alemadlei-tech** [wodby/nginx#8]
In theory NGINX_HIDE_50x_ERRORS allows to exclude the creation of the error handler. However, leaving empty, setting 0 "Off" or "0" still generates the location section.

What is the value that we need to put there?

This is the definition on my docker-compose.yml file

```
  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
      NGINX_HIDE_50x_ERRORS:
    volumes:
      - ./docroot:/var/www/html:cached
```
