### ISSUE TITLE
ancestor violates the following Content Security Policy directive: "frame-ancestors" Drupal 10

### ISSUE THREAD

**Issue by Eduardo-Morales-Alberti** [wodby/nginx#88]
After upgrading to drupal 10 we got the following error:
```
Refused to frame 'http://mysite.docker.localhost:8000/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```
The Nginx is configured as:
.env:
```
NGINX_TAG=1.19-5.33.0
NGINX_VHOST_PRESET=drupal10
```

docker-compose.yml
```
  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
````

The readme says that Drupal preset https://github.com/wodby/nginx#drupal should have "frame-ancestors 'self'" but in the error is 'none'.
We tried to override the header, but we got the same error, but changed it to:
```
Refused to frame 'http://mysite.docker.localhost:8000/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

Our solution was to use:
```
NGINX_HEADERS_CONTENT_SECURITY_POLICY: "frame-ancestors self http://${PROJECT_BASE_URL}:8000 http://nginx"
```

But this error was given after upgrading to Drupal 10.

Any clue?

Documentation of header frame-ancestors:
https://content-security-policy.com/frame-ancestors/#:~:text=Using%20frame%2Dancestors%20'none',a%20frame%20or%20iframe%20tag.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
